/**
 * Stable entry for the v6 battle kernel.
 * Pure functions for the next package. No turn driver, no monster placement, no React.
 */

export type {
  Aura,
  AuraQuery,
  BattleState,
  CardDefinition,
  CardInstance,
  CardSetup,
  CellId,
  Choice,
  CoverThreshold,
  CreateBattleInput,
  EffectRequest,
  FieldQuery,
  ForceReason,
  LeavePrompt,
  ListenerEvent,
  NegativeKind,
  Opcode,
  PendingEvent,
  PlayRejection,
  PlayRequest,
  PlayResult,
  Reaction,
  ReactionSubject,
  RemovalReason,
  RemoveCondition,
  RuleType,
  Side,
  TargetSpec,
  TurnEndPrompt,
  TurnEndStep,
  Winner,
  Zone,
} from './types';

export { CELL_IDS, CHAIN_DEPTH_LIMIT, HAND_LIMIT, isCellId, mirrorCell, orthogonalNeighbors } from './board';

export {
  activeCoverThreshold,
  adjacentFieldCards,
  advanceTurnEnd,
  advanceTurnStart,
  boardInstanceIds,
  cardAt,
  cardsInZone,
  checkZero,
  createBattle,
  currentPoints,
  appraiseBoard,
  evaluateForceSettlement,
  executeOpcodes,
  hasLegalPlay,
  inspectPlay,
  judgeWinner,
  legalPlayTargets,
  occupiedCount,
  playCard,
  pendingTurnEndTargets,
  raiseForceSettlement,
  resolveLeaveChoice,
  resolveTurnEndEffects,
  runEnemyTurnEndEffects,
  shufflePrintedIntoDeck,
  runTurnEndEffects,
  runTurnStartEffects,
  tickTimers,
  totalPoints,
  unseal,
} from './battle';
