<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Pcd.Sim</RootNamespace>
    <AssemblyName>Pcd.Sim</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pcd.HostCatalog\Pcd.HostCatalog.csproj" />
    <ProjectReference Include="..\Pcd.Kernel\Pcd.Kernel.csproj" />
  </ItemGroup>
</Project>
