import { PAL } from '../../palette'
import type { SpriteDef } from '../../dsl'

/** 巡猎者：皮甲、短披风、弓斜背、腰上金漆罐。 */
export const RANGER: SpriteDef = {
  id: 'char.pca00',
  size: [16, 20],
  anchor: [8, 20],
  palette: {
    o: PAL.ink,
    h: PAL.brown,
    H: PAL.pack,
    G: PAL.cream,
    e: PAL.eye,
    s: PAL.belly,
    S: PAL.bellyD,
    c: PAL.wood2,
    C: PAL.wood1,
    p: PAL.pack,
    l: PAL.gold,
    y: PAL.brown,
    w: PAL.wood1,
  },
  parts: {
    body: {
      offset: [0, 0],
      frames: [
        [
          '................',
          '....oooo........',
          '...ohhhho.......',
          '...ohGhhHo......',
          '...oheehho......',
          '....oSSso.......',
          '...occccco.w....',
          '..opcccccpo.w...',
          '..occcclcccow...',
          '..oCcccccCoow...',
          '...occcccco.....',
          '....oCCCCo......',
          '....os..so......',
          '....ys..sy......',
          '...ooo..ooo.....',
          '................',
          '................',
          '................',
          '................',
          '................',
        ],
        [
          '................',
          '................',
          '....oooo........',
          '...ohhhho.......',
          '...ohGhhHo......',
          '...oheehho......',
          '....oSSso.......',
          '...occccco.w....',
          '..opcccccpo.w...',
          '..occcclcccow...',
          '..oCcccccCoow...',
          '...oCCCCCo......',
          '....os..so......',
          '....ys..sy......',
          '...ooo..ooo.....',
          '................',
          '................',
          '................',
          '................',
          '................',
        ],
        [
          '................',
          '....oooo........',
          '...ohhhho.......',
          '...ohGhhHo......',
          '...ohsssho......',
          '....oSSso.......',
          '...occccco.w....',
          '..opcccccpo.w...',
          '..occcclcccow...',
          '..oCcccccCoow...',
          '...occcccco.....',
          '....oCCCCo......',
          '....os..so......',
          '....ys..sy......',
          '...ooo..ooo.....',
          '................',
          '................',
          '................',
          '................',
          '................',
        ],
      ],
    },
  },
  compose: ['body'],
  animations: {
    idle: { fps: 3, body: [0, 1, 0, 2] },
    hurt: { body: 0 },
  },
}

/** 唤骨者：灰袍活人、骨灰扑面、骨杖、领口肋骨饰。 */
export const NECRO: SpriteDef = {
  id: 'char.pcb00',
  size: [16, 20],
  anchor: [8, 20],
  palette: {
    o: PAL.ink,
    h: PAL.gray1,
    H: PAL.ink2,
    G: PAL.cream,
    e: PAL.eye,
    s: PAL.belly,
    S: PAL.bellyD,
    g: PAL.gray1,
    r: PAL.cream,
    p: PAL.purpleD,
    y: PAL.brown,
    k: PAL.cream,
  },
  parts: {
    body: {
      offset: [0, 0],
      frames: [
        [
          '................',
          '.....oooo.......',
          '....ohhhho......',
          '...ohhGhhHo.k...',
          '...ohheehho.k...',
          '....oSSso...k...',
          '...ogggggo..k...',
          '..oggrrgggo.k...',
          '..ogggpgggook...',
          '..ogggggggo.k...',
          '...ogggggo..k...',
          '....oGGGGo..k...',
          '....os..so.k....',
          '....ys..sy.k....',
          '...ooo..ooook...',
          '................',
          '................',
          '................',
          '................',
          '................',
        ],
        [
          '................',
          '................',
          '.....oooo.......',
          '....ohhhho......',
          '...ohhGhhHo.k...',
          '...ohheehho.k...',
          '....oSSso...k...',
          '...ogggggo..k...',
          '..oggrrgggo.k...',
          '..ogggpgggook...',
          '..ogggggggo.k...',
          '....oGGGGo..k...',
          '....os..so.k....',
          '....ys..sy.k....',
          '...ooo..ooook...',
          '................',
          '................',
          '................',
          '................',
          '................',
        ],
        [
          '................',
          '.....oooo.......',
          '....ohhhho......',
          '...ohhGhhHo.k...',
          '...ohhsssho.k...',
          '....oSSso...k...',
          '...ogggggo..k...',
          '..oggrrgggo.k...',
          '..ogggpgggook...',
          '..ogggggggo.k...',
          '...ogggggo..k...',
          '....oGGGGo..k...',
          '....os..so.k....',
          '....ys..sy.k....',
          '...ooo..ooook...',
          '................',
          '................',
          '................',
          '................',
          '................',
        ],
      ],
    },
  },
  compose: ['body'],
  animations: {
    idle: { fps: 3, body: [0, 1, 0, 2] },
    hurt: { body: 0 },
  },
}

/** 司油者：锈白法衣、油渍、铜香炉。 */
export const PRIEST: SpriteDef = {
  id: 'char.pcc00',
  size: [16, 20],
  anchor: [8, 20],
  palette: {
    o: PAL.ink,
    h: PAL.pack,
    H: PAL.brown,
    G: PAL.cream,
    e: PAL.eye,
    s: PAL.belly,
    S: PAL.bellyD,
    c: PAL.cream,
    C: PAL.paperD,
    u: PAL.copper,
    l: PAL.gold,
    d: PAL.dai,
    y: PAL.brown,
  },
  parts: {
    body: {
      offset: [0, 0],
      frames: [
        [
          '................',
          '.....oooo.......',
          '....ohhhho......',
          '...ohhGhhHo.....',
          '...ohheehho.....',
          '....oSSso.......',
          '...occcccco.....',
          '..occcccccco.u..',
          '..occcdlcccou...',
          '..oCcccccCco.u..',
          '...occcccco.....',
          '....oCCCCo......',
          '....os..so......',
          '....ys..sy......',
          '...ooo..ooo.....',
          '................',
          '................',
          '................',
          '................',
          '................',
        ],
        [
          '................',
          '................',
          '.....oooo.......',
          '....ohhhho......',
          '...ohhGhhHo.....',
          '...ohheehho.....',
          '....oSSso.......',
          '...occcccco.....',
          '..occcccccco.u..',
          '..occcdlcccou...',
          '..oCcccccCco.u..',
          '....oCCCCo......',
          '....os..so......',
          '....ys..sy......',
          '...ooo..ooo.....',
          '................',
          '................',
          '................',
          '................',
          '................',
        ],
        [
          '................',
          '.....oooo.......',
          '....ohhhho......',
          '...ohhGhhHo.....',
          '...ohhsssho.....',
          '....oSSso.......',
          '...occcccco.....',
          '..occcccccco.u..',
          '..occcdlcccou...',
          '..oCcccccCco.u..',
          '...occcccco.....',
          '....oCCCCo......',
          '....os..so......',
          '....ys..sy......',
          '...ooo..ooo.....',
          '................',
          '................',
          '................',
          '................',
          '................',
        ],
      ],
    },
  },
  compose: ['body'],
  animations: {
    idle: { fps: 3, body: [0, 1, 0, 2] },
    hurt: { body: 0 },
  },
}

export const AVATARS: SpriteDef[] = [RANGER, NECRO, PRIEST]
