import { PAL } from '../../palette'
import type { SpriteDef } from '../../dsl'

/** 化身：坐在桌边的人，胸口一盏灯。idle 两拍呼吸 + 一拍眨眼。 */
export const AVATAR: SpriteDef = {
  id: 'char.avatar',
  size: [16, 20],
  anchor: [8, 20],
  palette: {
    o: PAL.ink,
    h: PAL.gray1,
    H: PAL.ink2,
    G: PAL.white,
    e: PAL.eye,
    s: PAL.belly,
    S: PAL.bellyD,
    c: PAL.wood2,
    C: PAL.wood1,
    l: PAL.lamp1,
    y: PAL.brown,
  },
  parts: {
    body: {
      offset: [0, 0],
      frames: [
        [
          '................',
          '......oooo......',
          '.....ohhhho.....',
          '....ohhGhhHo....',
          '....ohheehho....',
          '.....ossoo......',
          '......sSSs......',
          '....occcccco....',
          '...occcclccco...',
          '...occcccccco...',
          '...oCccccccCo...',
          '....occcccco....',
          '.....oCCCCo.....',
          '.....os..so.....',
          '.....ys..sy.....',
          '....ooo..ooo....',
          '................',
          '................',
          '................',
          '................',
        ],
        [
          '................',
          '................',
          '......oooo......',
          '.....ohhhho.....',
          '....ohhGhhHo....',
          '....ohheehho....',
          '.....ossoo......',
          '.....sSSSSs.....',
          '....occcccco....',
          '...occcclccco...',
          '...occcccccco...',
          '...oCccccccCo...',
          '....oCCCCCCo....',
          '.....os..so.....',
          '.....ys..sy.....',
          '....ooo..ooo....',
          '................',
          '................',
          '................',
          '................',
        ],
        [
          '................',
          '......oooo......',
          '.....ohhhho.....',
          '....ohhGhhHo....',
          '....ohhsssho....',
          '.....ossoo......',
          '......sSSs......',
          '....occcccco....',
          '...occcclccco...',
          '...occcccccco...',
          '...oCccccccCo...',
          '....occcccco....',
          '.....oCCCCo.....',
          '.....os..so.....',
          '.....ys..sy.....',
          '....ooo..ooo....',
          '................',
          '................',
          '................',
          '................',
        ],
      ],
    },
  },
  compose: ['body'],
  animations: {
    idle: { fps: 3, body: [0, 1, 0, 2] },
    hurt: { body: 0 },
  },
}
