import { PAL } from '../../palette'
import type { SpriteDef } from '../../dsl'

/** 地图上的头像。脚底锚点，走路时由场景左右摇。 */

const RANGER: SpriteDef = {
  id: 'char.head.a',
  size: [16, 16],
  anchor: [8, 16],
  palette: {
    o: PAL.ink,
    h: PAL.brown,
    H: PAL.pack,
    G: PAL.cream,
    e: PAL.eye,
    s: PAL.belly,
    c: PAL.wood2,
    C: PAL.wood1,
    p: PAL.pack,
    l: PAL.gold,
  },
  parts: {
    body: {
      offset: [0, 0],
      frames: [
        [
          '................',
          '...oooooo.......',
          '..ohhhhHHo......',
          '..ohGGhhHo......',
          '..oheehhHo......',
          '...osssso.......',
          '..occcccco......',
          '.opccccccpo.....',
          '.occlllccco.....',
          '..occcccco......',
          '...oCCCCo.......',
          '................',
          '................',
          '................',
          '................',
          '................',
        ],
        [
          '...oooooo.......',
          '..ohhhhHHo......',
          '..ohGGhhHo......',
          '..ohsshhHo......',
          '...osssso.......',
          '..occcccco......',
          '.opccccccpo.....',
          '.occlllccco.....',
          '..occcccco......',
          '...oCCCCo.......',
          '................',
          '................',
          '................',
          '................',
          '................',
          '................',
        ],
      ],
    },
  },
  compose: ['body'],
  animations: {
    idle: { fps: 2, body: [0, 0, 0, 1] },
    walk: { fps: 8, body: [0, 1] },
  },
}

const NECRO: SpriteDef = {
  id: 'char.head.b',
  size: [16, 16],
  anchor: [8, 16],
  palette: {
    o: PAL.ink,
    h: PAL.gray1,
    H: PAL.ink2,
    G: PAL.cream,
    e: PAL.eye,
    s: PAL.belly,
    p: PAL.purpleD,
  },
  parts: {
    body: {
      offset: [0, 0],
      frames: [
        [
          '................',
          '....oooo........',
          '...ohhhhho......',
          '..ohhGGhhHo.....',
          '..ohheehhHo.....',
          '...ossssso......',
          '..opppppppo.....',
          '.opppppppppo....',
          '..opGppGppo.....',
          '...opppppo......',
          '....oooo........',
          '................',
          '................',
          '................',
          '................',
          '................',
        ],
        [
          '....oooo........',
          '...ohhhhho......',
          '..ohhGGhhHo.....',
          '..ohhsshhHo.....',
          '...ossssso......',
          '..opppppppo.....',
          '.opppppppppo....',
          '..opGppGppo.....',
          '...opppppo......',
          '....oooo........',
          '................',
          '................',
          '................',
          '................',
          '................',
          '................',
        ],
      ],
    },
  },
  compose: ['body'],
  animations: {
    idle: { fps: 2, body: [0, 0, 0, 1] },
    walk: { fps: 8, body: [0, 1] },
  },
}

const PRIEST: SpriteDef = {
  id: 'char.head.c',
  size: [16, 16],
  anchor: [8, 16],
  palette: {
    o: PAL.ink,
    h: PAL.pack,
    H: PAL.brown,
    G: PAL.paper,
    e: PAL.eye,
    s: PAL.belly,
    c: PAL.cream,
    C: PAL.paperD,
    u: PAL.copper,
    l: PAL.gold,
  },
  parts: {
    body: {
      offset: [0, 0],
      frames: [
        [
          '................',
          '....oooo........',
          '...ohhhhho......',
          '..ohhGGhhHo.....',
          '..ohheehhHo.....',
          '...ossssso......',
          '..occccccco.....',
          '.occuclcccco....',
          '..occccccco.....',
          '...oCCCCo.......',
          '................',
          '................',
          '................',
          '................',
          '................',
          '................',
        ],
        [
          '....oooo........',
          '...ohhhhho......',
          '..ohhGGhhHo.....',
          '..ohhsshhHo.....',
          '...ossssso......',
          '..occccccco.....',
          '.occuclcccco....',
          '..occccccco.....',
          '...oCCCCo.......',
          '................',
          '................',
          '................',
          '................',
          '................',
          '................',
          '................',
        ],
      ],
    },
  },
  compose: ['body'],
  animations: {
    idle: { fps: 2, body: [0, 0, 0, 1] },
    walk: { fps: 8, body: [0, 1] },
  },
}

export const HEADS: SpriteDef[] = [RANGER, NECRO, PRIEST]
