import type { CardDefinition, NameKind, OwnerKind, RuleKind } from './types'

function enemyCard(input: {
  slug: string
  name: string
  ownerKind: OwnerKind
  ruleKind: RuleKind
  nameKind: NameKind
  basePower: number | null
  powerFrom?: 'generator'
  timing: string
  target: string
  effectText: string
  keywords: string[]
  origin: 'enemyOnly' | 'token'
  orphan?: boolean
}): CardDefinition {
  return {
    id: `card.${input.ownerKind === 'token' ? 'token' : 'enemy'}.${input.slug}`,
    name: input.name,
    ownerKind: input.ownerKind,
    ruleKind: input.ruleKind,
    nameKind: input.nameKind,
    basePower: input.basePower,
    ...(input.powerFrom ? { powerFrom: input.powerFrom } : {}),
    school: null,
    rarity: null,
    effectText: input.effectText,
    timing: input.timing,
    target: input.target,
    origin: input.origin,
    keywords: input.keywords,
    pool: 'playable',
    orphan: input.orphan ?? false,
  }
}

export const enemyCards: CardDefinition[] = [
  enemyCard({
    slug: 'runaway-machine',
    name: '失控机械',
    ownerKind: 'enemyOnly',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 5,
    timing: '反应：玩家牌打出到相邻格',
    target: '那张牌',
    effectText: '驻场，为其添加解析标记',
    keywords: ['相邻', '驻场', '解析标记'],
    origin: 'enemyOnly',
  }),
  enemyCard({
    slug: 'heavy-strike',
    name: '大力打击',
    ownerKind: 'enemyOnly',
    ruleKind: 'permanent',
    nameKind: 'concept',
    basePower: 5,
    timing: '无',
    target: '无',
    effectText: '无效果',
    keywords: [],
    origin: 'enemyOnly',
    orphan: true,
  }),
  enemyCard({
    slug: 'closing-in',
    name: '逼近',
    ownerKind: 'enemyOnly',
    ruleKind: 'permanent',
    nameKind: 'concept',
    basePower: 2,
    timing: '入场',
    target: '自身',
    effectText: '有相邻玩家牌时点数 +2',
    keywords: ['入场', '相邻'],
    origin: 'enemyOnly',
    orphan: true,
  }),
  enemyCard({
    slug: 'ambush',
    name: '偷袭',
    ownerKind: 'enemyOnly',
    ruleKind: 'permanent',
    nameKind: 'concept',
    basePower: 2,
    timing: '入场',
    target: '随机 1 张相邻玩家牌',
    effectText: '使其点数 -1',
    keywords: ['入场', '相邻'],
    origin: 'enemyOnly',
    orphan: true,
  }),
  enemyCard({
    slug: 'hive',
    name: '蜂巢',
    ownerKind: 'enemyOnly',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 3,
    timing: '己方回合结束',
    target: '本卡的一个随机正交相邻空格',
    effectText: '生成工蜂。没有空格则不生成',
    keywords: ['相邻'],
    origin: 'enemyOnly',
  }),
  enemyCard({
    slug: 'worker-bee',
    name: '工蜂',
    ownerKind: 'token',
    ruleKind: 'permanent',
    nameKind: 'token',
    basePower: 1,
    timing: '无',
    target: '无',
    effectText: '无效果，燃尽',
    keywords: ['燃尽'],
    origin: 'token',
  }),
  enemyCard({
    slug: 'ancient-mirror',
    name: '古镜',
    ownerKind: 'enemyOnly',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 4,
    timing: '反应：己方牌打出到敌方牌的镜像格',
    target: '那张己方牌',
    effectText: '使其点数 +2',
    keywords: ['镜像'],
    origin: 'enemyOnly',
  }),
  enemyCard({
    slug: 'crow-nest',
    name: '鸦巢',
    ownerKind: 'enemyOnly',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 2,
    timing: '反应：任意占场卡离场',
    target: '自身',
    effectText: '点数 +2',
    keywords: ['离场'],
    origin: 'enemyOnly',
  }),
  enemyCard({
    slug: 'lectern',
    name: '讲经台',
    ownerKind: 'enemyOnly',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 3,
    timing: '己方回合开始',
    target: '敌方信仰池',
    effectText: '获得 2 点信仰',
    keywords: ['信仰'],
    origin: 'enemyOnly',
  }),
  enemyCard({
    slug: 'dissection-table',
    name: '解剖台',
    ownerKind: 'enemyOnly',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 5,
    timing: '反应：敌方（玩家）获得解析标记',
    target: '自身',
    effectText: '点数 +1',
    keywords: ['解析标记'],
    origin: 'enemyOnly',
  }),
  enemyCard({
    slug: 'twin-mirror',
    name: '双生镜',
    ownerKind: 'enemyOnly',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 3,
    timing: '驻场光环',
    target: '自身',
    effectText: '若镜像格有己方牌，点数 +2',
    keywords: ['镜像', '驻场'],
    origin: 'enemyOnly',
  }),
  enemyCard({
    slug: 'mirror-shade',
    name: '镜影',
    ownerKind: 'token',
    ruleKind: 'permanent',
    nameKind: 'token',
    basePower: null,
    powerFrom: 'generator',
    timing: '无',
    target: '无',
    effectText: '无效果，燃尽。点数 = 向下取整（触发卡基础点数 / 2）',
    keywords: ['燃尽'],
    origin: 'token',
  }),
  enemyCard({
    slug: 'silence-pillar',
    name: '缄默刑柱',
    ownerKind: 'enemyOnly',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 5,
    timing: '反应：敌方被封印',
    target: '自身',
    effectText: '点数 +2',
    keywords: ['封印'],
    origin: 'enemyOnly',
  }),
  enemyCard({
    slug: 'great-bell',
    name: '大钟',
    ownerKind: 'enemyOnly',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 6,
    timing: '计时 3',
    target: '无',
    effectText: '满足特殊强制结算',
    keywords: ['计时'],
    origin: 'enemyOnly',
  }),
  enemyCard({
    slug: 'clockwork-guard',
    name: '发条卫兵',
    ownerKind: 'enemyOnly',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 4,
    timing: '驻场规则',
    target: '己方的大钟',
    effectText: '大钟不能被点数小于 10 的牌覆盖',
    keywords: ['驻场', '覆盖'],
    origin: 'enemyOnly',
  }),
  enemyCard({
    slug: 'called-core',
    name: '应召之核',
    ownerKind: 'enemyOnly',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 8,
    timing: '驻场规则；另有己方回合开始',
    target: '自身',
    effectText: '不能被点数小于 14 的牌覆盖。回合开始点数 +1',
    keywords: ['驻场', '覆盖'],
    origin: 'enemyOnly',
  }),
  enemyCard({
    slug: 'babble',
    name: '呓语',
    ownerKind: 'enemyOnly',
    ruleKind: 'spell',
    nameKind: 'concept',
    basePower: null,
    timing: '被玩家抽到',
    target: '玩家场上点数最高的牌，并列取格号最小',
    effectText: '点数 -2，然后本卡进弃牌堆。不占手牌、不消耗出牌、不补抽',
    keywords: [],
    origin: 'enemyOnly',
  }),
  enemyCard({
    slug: 'afterimage',
    name: '残影',
    ownerKind: 'token',
    ruleKind: 'permanent',
    nameKind: 'token',
    basePower: null,
    powerFrom: 'generator',
    timing: '无',
    target: '无',
    effectText: '无效果，燃尽',
    keywords: ['燃尽'],
    origin: 'token',
  }),
]
