import type { MonsterDefinition } from './types'

export const monsters: MonsterDefinition[] = [
  {
    id: 'runaway-machine',
    name: '失控机械',
    tier: 'intro',
    elLabel: '29，图上标成基准',
    skills: [],
    presets: [{ cell: 5, cardName: '失控机械' }],
    pollutedCells: [],
    intents: ['弱点采样机', '弱点攻击器', '攻击炮台'],
    placement: '通用落位',
    rewardGold: 50,
    rewardCardNames: ['显微镜', '攻击炮台', '弱点采样机'],
    rewardHugeCardBack: false,
  },
  {
    id: 'patrol-swarm',
    name: '巡检蜂群',
    tier: 'tier1',
    elLabel: '24，低于教学关，这是文档原数',
    skills: [],
    presets: [{ cell: 5, cardName: '蜂巢' }],
    pollutedCells: [],
    intents: ['巡检探头', '测绘员', '收容钳'],
    placement: '通用落位',
    rewardGold: 50,
    rewardCardNames: ['巡检探头', '测绘员', '收容钳', '定点清除'],
    rewardHugeCardBack: false,
  },
  {
    id: 'preaching-band',
    name: '布道团',
    tier: 'tier1',
    elLabel: '28',
    skills: [],
    presets: [{ cell: 2, cardName: '讲经台' }],
    pollutedCells: [],
    intents: ['辅祭', '神圣骑士', '审判官'],
    placement: '通用落位',
    rewardGold: 50,
    rewardCardNames: ['辅祭', '神圣骑士', '审判官', '祷告灯'],
    rewardHugeCardBack: false,
  },
  {
    id: 'mirror-person',
    name: '镜中人',
    tier: 'tier1',
    elLabel: '30',
    skills: [],
    presets: [{ cell: 5, cardName: '古镜' }],
    pollutedCells: [],
    intents: ['镜匠', '银镜', '双生子'],
    placement:
      '镜匠：优先落在点数最高玩家牌的镜像空格。银镜：优先落在点数最高的己方牌的镜像空格。双生子：优先落在任意一张己方牌的镜像空格。都不满足时通用落位',
    rewardGold: 50,
    rewardCardNames: ['镜匠', '银镜', '双生子', '镜面翻转'],
    rewardHugeCardBack: false,
  },
  {
    id: 'rust-colossus',
    name: '锈蚀巨像',
    tier: 'tier2',
    elLabel: '二阶',
    skills: [],
    presets: [],
    pollutedCells: [],
    intents: ['钻心器', '霸占者', '过载电池'],
    placement: '钻心器、霸占者、过载电池：覆盖优先',
    rewardGold: 60,
    rewardCardNames: ['钻心器', '霸占者', '过载电池', '调取图纸'],
    rewardHugeCardBack: false,
  },
  {
    id: 'carrion-crows',
    name: '食腐鸦群',
    tier: 'tier2',
    elLabel: '29',
    skills: [],
    presets: [{ cell: 1, cardName: '鸦巢' }],
    pollutedCells: [],
    intents: ['提灯人', '托孤者', '守墓人'],
    placement: '通用落位',
    rewardGold: 50,
    rewardCardNames: ['提灯人', '托孤者', '守墓人', '引魂铃', '骨匠'],
    rewardHugeCardBack: false,
  },
  {
    id: 'anatomist',
    name: '解剖学家',
    tier: 'elite',
    elLabel: '39',
    skills: ['活体解析'],
    presets: [{ cell: 5, cardName: '解剖台' }],
    pollutedCells: [],
    intents: ['收容钳', '攻击炮台', '标本柜', '激光扫描仪'],
    placement:
      '收容钳、标本柜：通用落位。攻击炮台、激光扫描仪：优先落在与玩家牌正交相邻数最少的空格，并列取格号最小；没有空格再按通用的覆盖步',
    rewardGold: 100,
    rewardCardNames: ['收容钳', '攻击炮台', '标本柜', '激光扫描仪', '逆向解析'],
    rewardHugeCardBack: false,
  },
  {
    id: 'silent-order',
    name: '缄默修会',
    tier: 'elite',
    elLabel: '40',
    skills: ['干扰'],
    presets: [{ cell: 5, cardName: '缄默刑柱' }],
    pollutedCells: [4, 6],
    intents: ['告解神父', '驱魔人', '大审判长'],
    placement:
      '告解神父：落在点数最高玩家牌的正交相邻空格，并封印那一张；没有这样的空格则通用落位。驱魔人：通用落位。大审判长：优先与玩家牌相邻最少的空格',
    rewardGold: 100,
    rewardCardNames: ['告解神父', '驱魔人', '大审判长', '庇佑祷词'],
    rewardHugeCardBack: false,
  },
  {
    id: 'mirror-witch',
    name: '镜渊魔女',
    tier: 'elite',
    elLabel: '43',
    skills: ['镜像反射'],
    presets: [
      { cell: 2, cardName: '双生镜' },
      { cell: 8, cardName: '双生镜' },
    ],
    pollutedCells: [],
    intents: ['黑镜', '夺舍者', '星盘'],
    placement:
      '黑镜：在自身是空格且镜像格也是空格的格子里，选与玩家牌相邻最多的，并列取格号最小。夺舍者：优先打在点数最高的己方镜影上并继承其点数；没有镜影则通用落位。星盘：优先落在己方牌的镜像空格，否则通用落位',
    rewardGold: 100,
    rewardCardNames: ['黑镜', '夺舍者', '星盘', '亡者低语', '冥河摆渡人'],
    rewardHugeCardBack: false,
  },
  {
    id: 'bell-warden',
    name: '钟楼守望者',
    tier: 'boss',
    elLabel: '49',
    skills: ['封锁'],
    presets: [
      { cell: 2, cardName: '大钟' },
      { cell: 8, cardName: '发条卫兵' },
    ],
    pollutedCells: [],
    intents: ['圣殿守卫', '计时器', '穿甲钻头'],
    placement: '圣殿守卫：优先大钟的正交相邻空格。计时器：优先点数最高玩家牌的镜像空格。穿甲钻头：覆盖优先',
    rewardGold: 150,
    rewardCardNames: ['圣殿守卫', '计时器', '穿甲钻头', '圣杯'],
    rewardHugeCardBack: true,
  },
  {
    id: 'the-caller',
    name: '呼唤者',
    tier: 'final',
    elLabel: '53',
    skills: ['呼唤', '呓语'],
    presets: [{ cell: 5, cardName: '应召之核' }],
    pollutedCells: [],
    intents: ['测绘员', '数据核心', '彼岸花', '圣女'],
    placement: '测绘员、数据核心：通用落位。彼岸花、圣女：优先与玩家牌相邻最少的空格',
    rewardGold: 200,
    rewardCardNames: ['测绘员', '数据核心', '彼岸花', '圣女'],
    rewardHugeCardBack: true,
  },
]
