import type { CardDefinition, CardOrigin, CardPool, NameKind, Rarity, RuleKind } from './types'

function mysteryCard(input: {
  slug: string
  name: string
  ruleKind: RuleKind
  nameKind: NameKind
  basePower: number | null
  rarity: Rarity
  origin: CardOrigin
  timing: string
  target: string
  effectText: string
  keywords: string[]
  pool?: CardPool
  notes?: string
}): CardDefinition {
  return {
    id: `card.mystery.${input.slug}`,
    name: input.name,
    ownerKind: 'player',
    ruleKind: input.ruleKind,
    nameKind: input.nameKind,
    basePower: input.basePower,
    school: 'mystery',
    rarity: input.rarity,
    effectText: input.effectText,
    timing: input.timing,
    target: input.target,
    origin: input.origin,
    keywords: input.keywords,
    pool: input.pool ?? 'playable',
    orphan: false,
    ...(input.notes ? { notes: input.notes } : {}),
  }
}

export const mysteryCards: CardDefinition[] = [
  mysteryCard({
    slug: 'crystal-ball',
    name: '水晶球',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 3,
    rarity: 'white',
    origin: 'existing',
    timing: '入场',
    target: '玩家从牌组顶最多 3 张里选 1',
    effectText: '选中的入手，其余移除',
    keywords: ['入场', '移除'],
  }),
  mysteryCard({
    slug: 'sage',
    name: '智者',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 2,
    rarity: 'blue',
    origin: 'existing',
    timing: '入场',
    target: '见 5.3',
    effectText: '献祭 1，获得弃牌堆卡牌的点数。对象未定义，禁止编进可用内容',
    keywords: ['入场', '献祭'],
    pool: 'excluded',
  }),
  mysteryCard({
    slug: 'altar',
    name: '祭坛',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 5,
    rarity: 'gold',
    origin: 'existing',
    timing: '入场',
    target: '自身',
    effectText: '献祭 3，本卡点数翻倍',
    keywords: ['入场', '献祭'],
  }),
  mysteryCard({
    slug: 'projector',
    name: '投影仪',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 4,
    rarity: 'white',
    origin: 'existing',
    timing: '入场',
    target: '自身的镜像空格',
    effectText: '献祭 2，在镜像格生成复制；其中一张离场则移除另一张。复制深度见 5.3',
    keywords: ['入场', '镜像', '离场', '移除', '献祭'],
    pool: 'playable',
    notes: '只有原件生成复制。复制品保留「一侧离场则移除另一侧」，不再拥有「献祭并生成复制」。',
  }),
  mysteryCard({
    slug: 'immortal-statue',
    name: '永生雕像',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 3,
    rarity: 'white',
    origin: 'existing',
    timing: '入场；离场',
    target: '无',
    effectText: '两个时机各把一张本卡的印刷复制洗入牌组',
    keywords: ['入场', '离场'],
  }),
  mysteryCard({
    slug: 'underworld-aid',
    name: '冥界来援',
    ruleKind: 'spell',
    nameKind: 'concept',
    basePower: null,
    rarity: 'white',
    origin: 'existing',
    timing: '打出',
    target: '玩家选 1 张场上占场卡',
    effectText: '己方弃牌堆每有一张，该牌点数 +2',
    keywords: [],
  }),
  mysteryCard({
    slug: 'devourer',
    name: '吞噬者',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 3,
    rarity: 'white',
    origin: 'existing',
    timing: '入场',
    target: '自身',
    effectText: '献祭 2，本卡点数 +3',
    keywords: ['入场', '献祭'],
  }),
  mysteryCard({
    slug: 'summon-soul',
    name: '招魂',
    ruleKind: 'spell',
    nameKind: 'concept',
    basePower: null,
    rarity: 'white',
    origin: 'existing',
    timing: '打出',
    target: '玩家从己方弃牌堆选 1 张',
    effectText: '放回手牌。弃牌堆空则不可打',
    keywords: [],
  }),
  mysteryCard({
    slug: 'possessor',
    name: '夺舍者',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 4,
    rarity: 'white',
    origin: 'existing',
    timing: '打出到己方格时的替换，同时视为入场',
    target: '一张己方场上牌，或按普通规则打空格/覆盖',
    effectText: '可以打到己方格：获得该卡当前点数，然后移除该卡并触发离场',
    keywords: ['入场', '离场', '移除', '覆盖'],
  }),
  mysteryCard({
    slug: 'gravekeeper',
    name: '守墓人',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 5,
    rarity: 'blue',
    origin: 'existing',
    timing: '反应：任意占场卡离场',
    target: '自身',
    effectText: '点数 +2',
    keywords: ['离场'],
  }),
  mysteryCard({
    slug: 'tombstone',
    name: '墓碑',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 2,
    rarity: 'white',
    origin: 'existing',
    timing: '离场',
    target: '无',
    effectText: '抽 1 张',
    keywords: ['离场'],
  }),
  mysteryCard({
    slug: 'clone-spell',
    name: '克隆术',
    ruleKind: 'spell',
    nameKind: 'concept',
    basePower: null,
    rarity: 'blue',
    origin: 'existing',
    timing: '打出',
    target: '玩家选 1 张己方场上牌，再选 1 个空格',
    effectText: '在空格生成它的复制',
    keywords: [],
  }),
  mysteryCard({
    slug: 'revenant',
    name: '复生者',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 4,
    rarity: 'blue',
    origin: 'existing',
    timing: '入场；离场',
    target: '自身',
    effectText: '入场：弃牌堆每有一张占场卡，点数 +1。离场：洗回牌组',
    keywords: ['入场', '离场'],
  }),
  mysteryCard({
    slug: 'wildfire-envoy',
    name: '燎原使者',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 4,
    rarity: 'blue',
    origin: 'existing',
    timing: '入场',
    target: '自身或牌组',
    effectText: '牌组 ≤5 时抽 1 且点数 +2；否则洗入一张复制',
    keywords: ['入场'],
  }),
  mysteryCard({
    slug: 'silver-mirror',
    name: '银镜',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 2,
    rarity: 'white',
    origin: 'intent',
    timing: '驻场光环',
    target: '镜像格上的己方牌',
    effectText: '该牌点数 +2',
    keywords: ['镜像', '驻场'],
  }),
  mysteryCard({
    slug: 'twins',
    name: '双生子',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 3,
    rarity: 'blue',
    origin: 'intent',
    timing: '入场',
    target: '镜像格上的己方牌，以及自身',
    effectText: '若镜像格有己方，双方点数各 +2',
    keywords: ['入场', '镜像'],
  }),
  mysteryCard({
    slug: 'mirror-wright',
    name: '镜匠',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 4,
    rarity: 'blue',
    origin: 'intent',
    timing: '入场',
    target: '镜像格上的敌方牌',
    effectText: '献祭 1；若镜像格有敌方，使其点数 -3',
    keywords: ['入场', '镜像', '献祭'],
  }),
  mysteryCard({
    slug: 'black-mirror',
    name: '黑镜',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 3,
    rarity: 'blue',
    origin: 'intent',
    timing: '反应：敌方打出到本卡镜像格',
    target: '那张刚打出的牌',
    effectText: '使其点数 -2',
    keywords: ['镜像'],
  }),
  mysteryCard({
    slug: 'mirror-flip',
    name: '镜面翻转',
    ruleKind: 'spell',
    nameKind: 'concept',
    basePower: null,
    rarity: 'white',
    origin: 'extra',
    timing: '打出',
    target: '玩家选 1 张镜像格为空、且不在格5 的己方牌',
    effectText: '移动到镜像格，抽 1 张。移动不触发入场或离场',
    keywords: ['入场', '镜像', '离场'],
  }),
  mysteryCard({
    slug: 'astrolabe',
    name: '星盘',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 4,
    rarity: 'gold',
    origin: 'intent',
    timing: '驻场光环',
    target: '每一张与另一张己方牌互为镜像的己方牌',
    effectText: '这些牌点数 +2',
    keywords: ['镜像', '驻场'],
  }),
  mysteryCard({
    slug: 'bloodletting',
    name: '放血',
    ruleKind: 'spell',
    nameKind: 'concept',
    basePower: null,
    rarity: 'white',
    origin: 'starterOrShop',
    timing: '打出',
    target: '无',
    effectText: '献祭 3，抽 2 张',
    keywords: ['献祭'],
  }),
  mysteryCard({
    slug: 'bone-wright',
    name: '骨匠',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 3,
    rarity: 'white',
    origin: 'extra',
    timing: '入场',
    target: '无',
    effectText: '献祭 2，抽 1 张',
    keywords: ['入场', '献祭'],
  }),
  mysteryCard({
    slug: 'departed-soul',
    name: '亡魂',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 4,
    rarity: 'white',
    origin: 'starterOrShop',
    timing: '被献祭、即将从牌组进弃牌堆',
    target: '自身',
    effectText: '改为加入手牌',
    keywords: ['献祭'],
  }),
  mysteryCard({
    slug: 'ash-urn',
    name: '骨灰瓮',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 3,
    rarity: 'blue',
    origin: 'starterOrShop',
    timing: '反应：己方成功执行一次献祭',
    target: '自身',
    effectText: '点数 +2',
    keywords: ['献祭'],
  }),
  mysteryCard({
    slug: 'whisper-of-the-dead',
    name: '亡者低语',
    ruleKind: 'spell',
    nameKind: 'concept',
    basePower: null,
    rarity: 'blue',
    origin: 'extra',
    timing: '打出',
    target: '玩家选 1 张敌方',
    effectText: '己方弃牌堆每张使其 -1，至多 -5',
    keywords: [],
  }),
  mysteryCard({
    slug: 'bone-eater',
    name: '食骨者',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 3,
    rarity: 'blue',
    origin: 'starterOrShop',
    timing: '入场',
    target: '玩家从己方弃牌堆选至多 4 张',
    effectText: '燃尽它们，每张使本卡点数 +2',
    keywords: ['入场', '燃尽'],
  }),
  mysteryCard({
    slug: 'styx-ferryman',
    name: '冥河摆渡人',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 4,
    rarity: 'gold',
    origin: 'extra',
    timing: '己方回合开始；另有驻场光环',
    target: '自身',
    effectText: '回合开始献祭 1。光环：弃牌堆每张，点数 +1',
    keywords: ['驻场', '献祭'],
  }),
  mysteryCard({
    slug: 'lantern-bearer',
    name: '提灯人',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 2,
    rarity: 'white',
    origin: 'intent',
    timing: '离场',
    target: '随机空格',
    effectText: '生成 2 点残影',
    keywords: ['离场'],
  }),
  mysteryCard({
    slug: 'reincarnator',
    name: '轮回者',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 4,
    rarity: 'white',
    origin: 'starterOrShop',
    timing: '离场',
    target: '牌组',
    effectText: '洗入一张基础点数 +2 的本卡复制',
    keywords: ['离场'],
  }),
  mysteryCard({
    slug: 'release',
    name: '解脱',
    ruleKind: 'spell',
    nameKind: 'concept',
    basePower: null,
    rarity: 'white',
    origin: 'starterOrShop',
    timing: '打出',
    target: '玩家选 1 张己方场上牌',
    effectText: '移除并触发离场，抽 2 张。没有己方牌则不可打',
    keywords: ['离场', '移除'],
  }),
  mysteryCard({
    slug: 'entruster',
    name: '托孤者',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 3,
    rarity: 'blue',
    origin: 'intent',
    timing: '离场',
    target: '玩家选 1 张其他己方场上牌；没有则无点数效果',
    effectText: '使其点数 +3',
    keywords: ['离场'],
  }),
  mysteryCard({
    slug: 'soul-bell',
    name: '引魂铃',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 3,
    rarity: 'blue',
    origin: 'extra',
    timing: '反应：其他己方占场卡离场',
    target: '无',
    effectText: '抽 1 张',
    keywords: ['离场'],
  }),
  mysteryCard({
    slug: 'raise-dead',
    name: '唤亡',
    ruleKind: 'spell',
    nameKind: 'concept',
    basePower: null,
    rarity: 'blue',
    origin: 'starterOrShop',
    timing: '打出',
    target: '玩家选弃牌堆中 1 张占场卡，再选 1 个空格',
    effectText: '该牌在空格入场。弃牌堆没有占场卡或没有空格则不可打',
    keywords: ['入场'],
  }),
  mysteryCard({
    slug: 'spider-lily',
    name: '彼岸花',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 2,
    rarity: 'gold',
    origin: 'intent',
    timing: '反应：其他己方占场卡离场',
    target: '随机空格',
    effectText: '生成 3 点残影',
    keywords: ['离场'],
  }),
]
