import type { CardDefinition, CardOrigin, NameKind, Rarity, RuleKind } from './types'

function religionCard(input: {
  slug: string
  name: string
  ruleKind: RuleKind
  nameKind: NameKind
  basePower: number | null
  rarity: Rarity
  origin: CardOrigin
  timing: string
  target: string
  effectText: string
  keywords: string[]
}): CardDefinition {
  return {
    id: `card.religion.${input.slug}`,
    name: input.name,
    ownerKind: 'player',
    ruleKind: input.ruleKind,
    nameKind: input.nameKind,
    basePower: input.basePower,
    school: 'religion',
    rarity: input.rarity,
    effectText: input.effectText,
    timing: input.timing,
    target: input.target,
    origin: input.origin,
    keywords: input.keywords,
    pool: 'playable',
    orphan: false,
  }
}

export const religionCards: CardDefinition[] = [
  religionCard({
    slug: 'priest',
    name: '神官',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 3,
    rarity: 'white',
    origin: 'existing',
    timing: '入场',
    target: '自身所属方',
    effectText: '获得 2 点信仰',
    keywords: ['入场', '信仰'],
  }),
  religionCard({
    slug: 'holy-emblem',
    name: '圣徽',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 3,
    rarity: 'white',
    origin: 'existing',
    timing: '入场',
    target: '自身',
    effectText: '消耗 2 点信仰，获得保护',
    keywords: ['入场', '保护', '信仰'],
  }),
  religionCard({
    slug: 'inquisitor',
    name: '审判官',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 2,
    rarity: 'white',
    origin: 'existing',
    timing: '入场',
    target: '玩家选 1 张敌方；布道团另有限制',
    effectText: '消耗 4 点信仰，移除一张敌方牌',
    keywords: ['入场', '移除', '信仰'],
  }),
  religionCard({
    slug: 'penitent',
    name: '忏悔者',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 4,
    rarity: 'gold',
    origin: 'existing',
    timing: '入场',
    target: '自身',
    effectText: '消耗所有信仰，每 1 点使点数 +1',
    keywords: ['入场', '信仰'],
  }),
  religionCard({
    slug: 'church-servant',
    name: '教会仆从',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 4,
    rarity: 'white',
    origin: 'existing',
    timing: '己方回合结束',
    target: '自身所属方',
    effectText: '获得 1 点信仰',
    keywords: ['信仰'],
  }),
  religionCard({
    slug: 'god-statue',
    name: '神的雕像',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 6,
    rarity: 'white',
    origin: 'existing',
    timing: '己方回合开始',
    target: '自身',
    effectText: '消耗 1 点信仰，点数 +2',
    keywords: ['信仰'],
  }),
  religionCard({
    slug: 'nun',
    name: '修女',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 4,
    rarity: 'white',
    origin: 'existing',
    timing: '入场',
    target: '自身所属方',
    effectText: '获得 2 点信仰',
    keywords: ['入场', '信仰'],
  }),
  religionCard({
    slug: 'blessing',
    name: '祝福',
    ruleKind: 'spell',
    nameKind: 'concept',
    basePower: null,
    rarity: 'white',
    origin: 'existing',
    timing: '打出',
    target: '玩家选 1 张己方场上牌',
    effectText: '消耗 2 点信仰，使其点数 +3',
    keywords: ['信仰'],
  }),
  religionCard({
    slug: 'holy-knight',
    name: '神圣骑士',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 5,
    rarity: 'blue',
    origin: 'existing',
    timing: '入场',
    target: '自身',
    effectText: '信仰 ≥4：获得保护且点数 +3。否则获得 1 点信仰',
    keywords: ['入场', '保护', '信仰'],
  }),
  religionCard({
    slug: 'resurrection-prayer',
    name: '还魂祷告',
    ruleKind: 'spell',
    nameKind: 'concept',
    basePower: null,
    rarity: 'gold',
    origin: 'existing',
    timing: '打出',
    target: '玩家选 1 张己方场上牌',
    effectText: '消耗 4 点信仰，给予返魂且点数 +2',
    keywords: ['返魂', '信仰'],
  }),
  religionCard({
    slug: 'choir',
    name: '唱诗班',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 6,
    rarity: 'white',
    origin: 'existing',
    timing: '计时 2',
    target: '自身所属方',
    effectText: '获得 3 点信仰',
    keywords: ['计时', '信仰'],
  }),
  religionCard({
    slug: 'acolyte',
    name: '辅祭',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 2,
    rarity: 'white',
    origin: 'intent',
    timing: '入场',
    target: '自身所属方',
    effectText: '获得 3 点信仰',
    keywords: ['入场', '信仰'],
  }),
  religionCard({
    slug: 'preacher',
    name: '布道者',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 3,
    rarity: 'white',
    origin: 'starterOrShop',
    timing: '反应：敌方打出一张牌',
    target: '自身所属方',
    effectText: '获得 1 点信仰',
    keywords: ['信仰'],
  }),
  religionCard({
    slug: 'censer',
    name: '香炉',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 3,
    rarity: 'white',
    origin: 'starterOrShop',
    timing: '反应：己方打出一张法术',
    target: '自身所属方',
    effectText: '获得 2 点信仰',
    keywords: ['信仰'],
  }),
  religionCard({
    slug: 'sacred-baptism',
    name: '圣火洗礼',
    ruleKind: 'spell',
    nameKind: 'concept',
    basePower: null,
    rarity: 'white',
    origin: 'starterOrShop',
    timing: '打出',
    target: '玩家选 1 张敌方',
    effectText: '消耗 3 点信仰，使其点数 -4',
    keywords: ['信仰'],
  }),
  religionCard({
    slug: 'archbishop',
    name: '大主教',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 3,
    rarity: 'blue',
    origin: 'starterOrShop',
    timing: '己方回合开始',
    target: '玩家选 1 张己方场上牌',
    effectText: '信仰 ≥6 时使其点数 +2，不消耗信仰',
    keywords: ['信仰'],
  }),
  religionCard({
    slug: 'miracle',
    name: '神迹',
    ruleKind: 'spell',
    nameKind: 'concept',
    basePower: null,
    rarity: 'blue',
    origin: 'starterOrShop',
    timing: '打出',
    target: '所有己方场上牌',
    effectText: '消耗 8 点信仰，这些牌点数 +2',
    keywords: ['信仰'],
  }),
  religionCard({
    slug: 'grail',
    name: '圣杯',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 3,
    rarity: 'gold',
    origin: 'extra',
    timing: '入场',
    target: '自身所属方的信仰池',
    effectText: '当前信仰翻倍',
    keywords: ['入场', '信仰'],
  }),
  religionCard({
    slug: 'prayer-lamp',
    name: '祷告灯',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 2,
    rarity: 'white',
    origin: 'extra',
    timing: '入场',
    target: '玩家选 1 张己方场上牌，可以是自己',
    effectText: '给予保护，并获得 1 点信仰',
    keywords: ['入场', '保护', '信仰'],
  }),
  religionCard({
    slug: 'temple-guard',
    name: '圣殿守卫',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 4,
    rarity: 'white',
    origin: 'intent',
    timing: '驻场规则',
    target: '自身',
    effectText: '不能被点数小于 8 的牌覆盖',
    keywords: ['驻场', '覆盖'],
  }),
  religionCard({
    slug: 'restoration-prayer',
    name: '复原祷言',
    ruleKind: 'spell',
    nameKind: 'concept',
    basePower: null,
    rarity: 'white',
    origin: 'starterOrShop',
    timing: '打出',
    target: '玩家选 1 张己方场上牌',
    effectText: '若当前基础+永久低于基础，恢复到基础；并给予保护',
    keywords: ['保护'],
  }),
  religionCard({
    slug: 'martyr',
    name: '殉道者',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 4,
    rarity: 'blue',
    origin: 'starterOrShop',
    timing: '离场',
    target: '玩家选 1 张己方场上牌',
    effectText: '给予返魂与保护。没有其他己方牌则无效果',
    keywords: ['离场', '保护', '返魂'],
  }),
  religionCard({
    slug: 'reliquary',
    name: '圣骸匣',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 3,
    rarity: 'blue',
    origin: 'starterOrShop',
    timing: '反应：己方一张牌的保护被消耗',
    target: '那张牌',
    effectText: '给予返魂',
    keywords: ['保护', '返魂'],
  }),
  religionCard({
    slug: 'aegis-litany',
    name: '庇佑祷词',
    ruleKind: 'spell',
    nameKind: 'concept',
    basePower: null,
    rarity: 'blue',
    origin: 'extra',
    timing: '打出',
    target: '默认 1 张己方；信仰 ≥3 时改为全体己方',
    effectText: '给予保护并清除一个负面。信仰 ≥3 的分支不消耗信仰',
    keywords: ['保护', '信仰'],
  }),
  religionCard({
    slug: 'saint',
    name: '圣女',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 4,
    rarity: 'gold',
    origin: 'intent',
    timing: '己方回合开始；另有驻场光环',
    target: '回合开始：玩家选 1 张己方。光环：所有拥有保护的己方',
    effectText: '给予保护。光环使有保护的己方点数 +1',
    keywords: ['驻场', '保护'],
  }),
  religionCard({
    slug: 'interdict',
    name: '禁令',
    ruleKind: 'spell',
    nameKind: 'concept',
    basePower: null,
    rarity: 'white',
    origin: 'starterOrShop',
    timing: '打出',
    target: '玩家选 1 张敌方',
    effectText: '封印它，抽 1 张',
    keywords: ['封印'],
  }),
  religionCard({
    slug: 'confessor',
    name: '告解神父',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 3,
    rarity: 'white',
    origin: 'intent',
    timing: '入场',
    target: '玩家选 1 张相邻敌方',
    effectText: '封印它',
    keywords: ['入场', '相邻', '封印'],
  }),
  religionCard({
    slug: 'exorcist',
    name: '驱魔人',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 3,
    rarity: 'white',
    origin: 'intent',
    timing: '入场',
    target: '玩家选 1 张当前点数 ≤3 的敌方',
    effectText: '移除它',
    keywords: ['入场', '移除'],
  }),
  religionCard({
    slug: 'scribe',
    name: '书记官',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 3,
    rarity: 'white',
    origin: 'starterOrShop',
    timing: '反应：敌方被封印，或敌方被移除',
    target: '自身所属方',
    effectText: '获得 2 点信仰。一次事件只加一次',
    keywords: ['封印', '移除', '信仰'],
  }),
  religionCard({
    slug: 'purgation',
    name: '净罪',
    ruleKind: 'spell',
    nameKind: 'concept',
    basePower: null,
    rarity: 'blue',
    origin: 'starterOrShop',
    timing: '打出',
    target: '玩家选 1 张被封印的敌方',
    effectText: '移除它',
    keywords: ['封印', '移除'],
  }),
  religionCard({
    slug: 'grand-inquisitor',
    name: '大审判长',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 4,
    rarity: 'gold',
    origin: 'intent',
    timing: '己方回合开始',
    target: '玩家选 1 张敌方；没有则无效果',
    effectText: '封印它',
    keywords: ['封印'],
  }),
]
