import type { CardDefinition, CardOrigin, NameKind, Rarity, RuleKind } from './types'

function scienceCard(input: {
  slug: string
  name: string
  ruleKind: RuleKind
  nameKind: NameKind
  basePower: number | null
  rarity: Rarity
  origin: CardOrigin
  timing: string
  target: string
  effectText: string
  keywords: string[]
}): CardDefinition {
  return {
    id: `card.science.${input.slug}`,
    name: input.name,
    ownerKind: 'player',
    ruleKind: input.ruleKind,
    nameKind: input.nameKind,
    basePower: input.basePower,
    school: 'science',
    rarity: input.rarity,
    effectText: input.effectText,
    timing: input.timing,
    target: input.target,
    origin: input.origin,
    keywords: input.keywords,
    pool: 'playable',
    orphan: false,
  }
}

export const scienceCards: CardDefinition[] = [
  scienceCard({
    slug: 'research-device',
    name: '科学研究器',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 4,
    rarity: 'white',
    origin: 'existing',
    timing: '己方回合结束',
    target: '玩家选 1 张相邻敌方；没有则无效果',
    effectText: '驻场，回合结束时为一张相邻敌方添加解析标记',
    keywords: ['相邻', '驻场', '解析标记'],
  }),
  scienceCard({
    slug: 'weakness-sampler',
    name: '弱点采样机',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 3,
    rarity: 'white',
    origin: 'existing',
    timing: '入场',
    target: '玩家选 1 张敌方',
    effectText: '选择一张敌方添加解析标记',
    keywords: ['入场', '解析标记'],
  }),
  scienceCard({
    slug: 'weakness-striker',
    name: '弱点攻击器',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 4,
    rarity: 'blue',
    origin: 'existing',
    timing: '入场',
    target: '玩家选 1 张有标记的敌方',
    effectText: '使其点数 -2',
    keywords: ['入场', '解析标记'],
  }),
  scienceCard({
    slug: 'microscope',
    name: '显微镜',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 4,
    rarity: 'gold',
    origin: 'existing',
    timing: '反应：敌方被打出到相邻格',
    target: '该次打出的那张',
    effectText: '驻场，为打出到相邻的敌方添加解析标记',
    keywords: ['相邻', '驻场', '解析标记'],
  }),
  scienceCard({
    slug: 'attack-turret',
    name: '攻击炮台',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 6,
    rarity: 'white',
    origin: 'existing',
    timing: '己方回合结束',
    target: '玩家选 1 张有标记的敌方',
    effectText: '驻场，使其点数 -2',
    keywords: ['驻场', '解析标记'],
  }),
  scienceCard({
    slug: 'examiner',
    name: '勘验员',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 4,
    rarity: 'white',
    origin: 'existing',
    timing: '入场',
    target: '所有相邻敌方，自动',
    effectText: '为所有相邻敌方添加解析标记',
    keywords: ['入场', '相邻', '解析标记'],
  }),
  scienceCard({
    slug: 'analyzer',
    name: '解析仪',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 4,
    rarity: 'white',
    origin: 'existing',
    timing: '入场',
    target: '自身',
    effectText: '若相邻有带解析标记的敌方，本卡点数 +2',
    keywords: ['入场', '相邻', '解析标记'],
  }),
  scienceCard({
    slug: 'timer',
    name: '计时器',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 6,
    rarity: 'blue',
    origin: 'existing',
    timing: '计时 2',
    target: '镜像格上的敌方，自动',
    effectText: '使其点数 -4，并添加解析标记',
    keywords: ['镜像', '计时', '解析标记'],
  }),
  scienceCard({
    slug: 'instant-reading',
    name: '瞬时判读',
    ruleKind: 'spell',
    nameKind: 'concept',
    basePower: null,
    rarity: 'blue',
    origin: 'existing',
    timing: '打出；迅捷',
    target: '玩家选 1 张敌方',
    effectText: '为其添加解析标记并抽 1 张。没有敌方则不可打',
    keywords: ['迅捷', '解析标记'],
  }),
  scienceCard({
    slug: 'patrol-probe',
    name: '巡检探头',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 2,
    rarity: 'white',
    origin: 'intent',
    timing: '入场；然后敌方回合结束',
    target: '入场：玩家选 1 张敌方。回合结束：随机 1 张未持标记的敌方',
    effectText: '入场加标记；驻场，敌方回合结束给随机未标记敌方加标记',
    keywords: ['入场', '驻场', '解析标记'],
  }),
  scienceCard({
    slug: 'cartographer',
    name: '测绘员',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 2,
    rarity: 'white',
    origin: 'intent',
    timing: '入场',
    target: '玩家选 1 张敌方，并自动包含其相邻敌方',
    effectText: '为选中的敌方及其所有相邻敌方添加解析标记',
    keywords: ['入场', '相邻', '解析标记'],
  }),
  scienceCard({
    slug: 'containment-clamp',
    name: '收容钳',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 3,
    rarity: 'blue',
    origin: 'intent',
    timing: '入场',
    target: '玩家选 1 张当前点数 ≤3 且有标记的敌方',
    effectText: '移除该牌',
    keywords: ['入场', '移除', '解析标记'],
  }),
  scienceCard({
    slug: 'pinpoint-purge',
    name: '定点清除',
    ruleKind: 'spell',
    nameKind: 'concept',
    basePower: null,
    rarity: 'blue',
    origin: 'extra',
    timing: '打出',
    target: '玩家选 1 张有标记的敌方',
    effectText: '点数 -4；若因此离场，抽 1 张',
    keywords: ['离场', '解析标记'],
  }),
  scienceCard({
    slug: 'chain-detonation',
    name: '连锁引爆',
    ruleKind: 'spell',
    nameKind: 'concept',
    basePower: null,
    rarity: 'blue',
    origin: 'starterOrShop',
    timing: '打出',
    target: '所有有标记的敌方，自动',
    effectText: '这些牌点数 -2，然后摘掉仍在场者的标记',
    keywords: ['解析标记'],
  }),
  scienceCard({
    slug: 'specimen-cabinet',
    name: '标本柜',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 4,
    rarity: 'blue',
    origin: 'intent',
    timing: '反应：有标记的敌方离场',
    target: '自身',
    effectText: '每当发生则点数 +2',
    keywords: ['离场', '解析标记'],
  }),
  scienceCard({
    slug: 'laser-scanner',
    name: '激光扫描仪',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 4,
    rarity: 'gold',
    origin: 'intent',
    timing: '己方回合结束',
    target: '所有有标记的敌方，自动',
    effectText: '这些牌点数 -1',
    keywords: ['解析标记'],
  }),
  scienceCard({
    slug: 'overload-battery',
    name: '过载电池',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 12,
    rarity: 'white',
    origin: 'intent',
    timing: '己方回合结束',
    target: '自身',
    effectText: '点数 -1',
    keywords: [],
  }),
  scienceCard({
    slug: 'armor-drill',
    name: '穿甲钻头',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 10,
    rarity: 'white',
    origin: 'intent',
    timing: '入场',
    target: '玩家选至多 2 张敌方',
    effectText: '为它们添加解析标记',
    keywords: ['入场', '解析标记'],
  }),
  scienceCard({
    slug: 'fetch-blueprint',
    name: '调取图纸',
    ruleKind: 'spell',
    nameKind: 'concept',
    basePower: null,
    rarity: 'white',
    origin: 'extra',
    timing: '打出',
    target: '玩家从牌组中选 1 张基础点数 ≥8 的占场卡',
    effectText: '加入手牌',
    keywords: [],
  }),
  scienceCard({
    slug: 'assembler',
    name: '装配工',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 2,
    rarity: 'white',
    origin: 'starterOrShop',
    timing: '入场',
    target: '玩家选 1 张手牌中的占场卡',
    effectText: '该牌点数 +3',
    keywords: ['入场'],
  }),
  scienceCard({
    slug: 'disassembly-bench',
    name: '拆解台',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 5,
    rarity: 'white',
    origin: 'starterOrShop',
    timing: '入场',
    target: '玩家选 1 张其他己方场上牌',
    effectText: '移除它并触发离场，本卡永久加上它被移除前的当前点数',
    keywords: ['入场', '离场', '移除'],
  }),
  scienceCard({
    slug: 'data-core',
    name: '数据核心',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 4,
    rarity: 'blue',
    origin: 'intent',
    timing: '入场',
    target: '自动，场上所有带标记的牌，双方都算',
    effectText: '每有一张，本卡点数 +2',
    keywords: ['入场', '解析标记'],
  }),
  scienceCard({
    slug: 'chief-engineer',
    name: '总工程师',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 4,
    rarity: 'gold',
    origin: 'starterOrShop',
    timing: '己方回合开始',
    target: '手牌中全部占场卡，自动',
    effectText: '这些牌点数 +1',
    keywords: [],
  }),
  scienceCard({
    slug: 'calibrator',
    name: '校准仪',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 2,
    rarity: 'white',
    origin: 'starterOrShop',
    timing: '入场',
    target: '玩家选 1 张己方场上牌，可以是自己【建议默认】',
    effectText: '添加解析标记并点数 +1',
    keywords: ['入场', '解析标记'],
  }),
  scienceCard({
    slug: 'full-checkup',
    name: '全面体检',
    ruleKind: 'spell',
    nameKind: 'concept',
    basePower: null,
    rarity: 'white',
    origin: 'starterOrShop',
    timing: '打出',
    target: '所有己方场上牌，自动',
    effectText: '添加解析标记，然后抽 1 张。场上没有己方牌也抽',
    keywords: ['解析标记'],
  }),
  scienceCard({
    slug: 'signal-amplifier',
    name: '信号放大器',
    ruleKind: 'permanent',
    nameKind: 'object',
    basePower: 4,
    rarity: 'blue',
    origin: 'starterOrShop',
    timing: '反应：任意牌首次获得解析标记',
    target: '自身',
    effectText: '点数 +1',
    keywords: ['解析标记'],
  }),
  scienceCard({
    slug: 'test-subject',
    name: '实验体',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 4,
    rarity: 'blue',
    origin: 'starterOrShop',
    timing: '己方回合结束',
    target: '自身',
    effectText: '若本卡有解析标记，点数 +2',
    keywords: ['解析标记'],
  }),
  scienceCard({
    slug: 'reverse-analysis',
    name: '逆向解析',
    ruleKind: 'spell',
    nameKind: 'concept',
    basePower: null,
    rarity: 'blue',
    origin: 'extra',
    timing: '打出',
    target: '玩家选 1 张有标记的牌，双方皆可',
    effectText: '摘掉标记前先结算：己方则点数 +4，敌方则点数 -4',
    keywords: ['解析标记'],
  }),
  scienceCard({
    slug: 'chief-researcher',
    name: '首席研究员',
    ruleKind: 'permanent',
    nameKind: 'person',
    basePower: 3,
    rarity: 'gold',
    origin: 'starterOrShop',
    timing: '驻场光环',
    target: '所有有标记的己方牌，自动',
    effectText: '这些牌点数 +2',
    keywords: ['驻场', '解析标记'],
  }),
]
